; Listing generated by Microsoft (R) Optimizing Compiler Version 19.10.25019.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	f
; Function compile flags: /Odtp
_TEXT	SEGMENT
f	PROC
; File e:\repo\myrepo\xathrya\assemblycode-reference\mapping\x86\c\src\000.empty.c
; Line 14
	ret	0
f	ENDP
_TEXT	ENDS
END
