; Listing generated by Microsoft (R) Optimizing Compiler Version 19.10.25019.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	f
; Function compile flags: /Odtp
_TEXT	SEGMENT
f	PROC
; File e:\repo\myrepo\xathrya\assemblycode-reference\mapping\x86\c\src\001.function-return.c
; Line 10
	mov	eax, 135				; 00000087H
; Line 11
	ret	0
f	ENDP
_TEXT	ENDS
END
