; Listing generated by Microsoft (R) Optimizing Compiler Version 19.10.25019.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	f
; Function compile flags: /Odtp
_TEXT	SEGMENT
a$ = 8
b$ = 16
f	PROC
; File e:\repo\myrepo\xathrya\assemblycode-reference\mapping\x86\c\src\002.function-args.c
; Line 9
	mov	DWORD PTR [rsp+16], edx
	mov	DWORD PTR [rsp+8], ecx
; Line 10
	mov	eax, DWORD PTR b$[rsp]
	mov	ecx, DWORD PTR a$[rsp]
	add	ecx, eax
	mov	eax, ecx
; Line 11
	ret	0
f	ENDP
_TEXT	ENDS
END
