; Listing generated by Microsoft (R) Optimizing Compiler Version 19.10.25019.0 

	TITLE	E:\Repo\MyRepo\Xathrya\AssemblyCode-Reference\Mapping\x86\C\src\001.function-return.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_f
; Function compile flags: /Odtp
_TEXT	SEGMENT
_f	PROC
; File e:\repo\myrepo\xathrya\assemblycode-reference\mapping\x86\c\src\001.function-return.c
; Line 9
	push	ebp
	mov	ebp, esp
; Line 10
	mov	eax, 135				; 00000087H
; Line 11
	pop	ebp
	ret	0
_f	ENDP
_TEXT	ENDS
END
