; Listing generated by Microsoft (R) Optimizing Compiler Version 19.10.25019.0 

	TITLE	E:\Repo\MyRepo\Xathrya\AssemblyCode-Reference\Mapping\x86\C\src\003.function-vars.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_f
PUBLIC	__real@40400000
EXTRN	__fltused:DWORD
;	COMDAT __real@40400000
CONST	SEGMENT
__real@40400000 DD 040400000r			; 3
CONST	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_f$ = -12						; size = 4
_i$ = -8						; size = 4
_c$ = -1						; size = 1
_f	PROC
; File e:\repo\myrepo\xathrya\assemblycode-reference\mapping\x86\c\src\003.function-vars.c
; Line 9
	push	ebp
	mov	ebp, esp
	sub	esp, 12					; 0000000cH
; Line 10
	mov	BYTE PTR _c$[ebp], 1
; Line 11
	mov	DWORD PTR _i$[ebp], 2
; Line 12
	movss	xmm0, DWORD PTR __real@40400000
	movss	DWORD PTR _f$[ebp], xmm0
; Line 13
	mov	esp, ebp
	pop	ebp
	ret	0
_f	ENDP
_TEXT	ENDS
END
